import type { Metadata } from "next";
import { Urbanist } from 'next/font/google';
import "../globals.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import { PrimeReactProvider } from 'primereact/api';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Add the weights you need
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={urbanist.className}
      >
        <PrimeReactProvider>
          <div className="flex flex-col">
            <Navbar />
            <div className="">
              {children}
            </div>
            <Footer />
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
